### ISSUE TITLE
<noscript>&#x3C;

### ISSUE THREAD

**Issue by gdbaldw** [modernweb-dev/rocket#186] opened 2021-07-02 14:03 UTC
https://github.com/modernweb-dev/rocket/blob/8df9a3e9c3e64c6e7c65e0f14566aeed1118db69/packages/launch/preset/_includes/_joiningBlocks/head/50-noscript.njk#L1

...compiles to...

`<noscript>&#x3C;link rel="stylesheet" href="{{ '/_assets/_static/noscript.css' | asset | url }}"/></noscript>`

**Comment by bennypowers** [comment] 2021-07-03 18:48
This is caused by parsers, particularly Parse5 but maybe also SAX-WASM needing to be either in script or noscript mode.

A flaky workaround is:

```js
eleventyConfig.addTransform('fix-noscript', content =>
  content
    .replace(/&#x26;#x3C;(link|style)/g, '<$1')
    .replace(/&#x26;(link|style)/g, '<$1')
    .replace(/&#x3C;(link|style)/g, '<$1')
);
```
I've been unable to get this to work reliably in a preset, but if you add it in your rocket config in the `eleventy` hook, should be G2G

**Comment by bennypowers** [comment] 2021-07-03 18:48
@gdbaldw You might be interested in tracking #179

**Comment by daKmoR** [comment] 2022-08-14 22:08
it seems that just works fine when using the new `@rocket/engine` version...

I put this in my page or template

```html
<noscript>
  <link rel="stylesheet" href="resolve:@rocket/spark/css/content.css" />
  <p>some <strong>stuff</strong></p>
</noscript>
```

and this comes out

```html
<noscript>
  <link rel="stylesheet" href="../../presets/spark/src/css/content.css">
  <p>some <strong>stuff</strong></p>
</noscript>
```

I'm closing this - if it's not working as expected feel free to reopen or to create a new issue 🤗

**Closed by daKmoR** 2022-08-14 22:08 UTC
